#!/usr/bin/env python3
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

from suaylang.vm import main as vm_main

if __name__ == "__main__":
    raise SystemExit(vm_main())
